name: Update PR Body Example
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs: 
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.pulls.update({
              pull_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'thomasthornton.cloud example'
            })